INPUT_FOLDER = testfiles/input
OUTPUT_FOLDER = testfiles/output
EXPECTED_FOLDER = testfiles/expected

all: clean_output run_tests

clean_output:
	rm -f $(OUTPUT_FOLDER)/*

run_tests:
	python test_ac.py
